[build]
  publish = "public"
  functions = "netlify/functions"

[[headers]]
  for = "/admin/*"
  [headers.values]
    X-Frame-Options = "DENY"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200
