[build]
  publish = "public"
  functions = "netlify/functions"

[[redirects]]
  from = "/api/get-data"
  to = "/.netlify/functions/get-data"
  status = 200
  force = true

[[redirects]]
  from = "/api/update-data"
  to = "/.netlify/functions/update-data"
  status = 200
  force = true
